### PR TITLE
Add ability to download pypy2.7 for macos and add CI

### PR DESCRIPTION
**Pull request by mattip**
- change the pydrofoil-from-sail CI run to run on both ubuntu and macos
- add a python script to print which tarball to download
- tweak the user-facing build documentation

CI will run x86_64 darwin, I checked that the Makefile works with arm64 darwin.

### CODE REVIEW

**Comment by mattip** [comment]
At some point we might think about running the build CI only when we [have a particular label](https://stackoverflow.com/questions/62325286/run-github-actions-when-pull-requests-have-a-specific-label) to save a few CI cycles

**Comment by cfbolz** [comment]
looks great, thank you! and agreed about running CI less often. (at the minimum we should be better at adding `[skip ci]` to the commit messages where it doesn't matter)

we should maybe document the need for having a `python3` installed now, on the `building_pydrofoil.md` page.

**Comment by cfbolz** [comment]
errors with "/pypy_binary/bin/python: cannot execute binary file" :-( I suspect that this is the binary signing problem?

**Comment by cfbolz** [comment]
maybe this would help: https://github.com/ninja-build/ninja/issues/1695

**Comment by cfbolz** [comment]
the test summarizer was broken because of the changes in the xml names, I tried to fix it.

**Comment by cfbolz** [comment]
I'm merging now, will fix potential problems with the test summarizer afterwards. Thanks Matti :blush:!

**Pull request merged**
